version: '3.7'

services:

###########################################
# Core Services
###########################################

  # WebApp
  ###########################################
  webapp:
    container_name: webapp
    hostname: webapp-docker-local
    build:
      context: ./services/webapp
      dockerfile: nginx124_php83_node20.dockerfile
      args:
        - XDEBUG_HOST_IP=${YOUR_HOST_IP}
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL=${GIT_EMAIL}
    volumes:
      - ./volumes/webapp:/var/www/html
      - ./services/webapp/default.conf:/etc/nginx/sites-available/default.conf
      - ./services/webapp/nginx.conf:/etc/nginx/nginx.conf
      - ./services/webapp/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./services/webapp/aliases.bashrc:/root/aliases.bashrc
    ports:
      - "${WEBAPP_NGINX_PORT}:80"
      - "${WEBAPP_NGINX_SSL_PORT}:443"
    environment:
      - PHP_ENABLE_XDEBUG=1
      - PHP_IDE_CONFIG=localhost
    networks:
      - webapp-network


###########################################
# Shared Services
###########################################

  # Redis
  ###########################################
  redis:
    container_name: redis_local
    hostname: redis-docker-local
    image: redis:7.2.4-alpine
    volumes:
      - ./volumes/data/redis/cache:/var/lib/redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - webapp-network

  # MySQL
  ###########################################
  mysqldb:
    container_name: mysqldb-local
    hostname: mysqldb-docker-local
    image: mysql:8.0.28
    command: mysqld --authentication-policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDB_DATABASE}"
      - "MYSQL_USER=${MYSQLDB_USER}"
      - "MYSQL_PASSWORD=${MYSQLDB_PASSWORD}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD='yes'"
    restart: always
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - ./volumes/data/mysql/storage/persist:/var/lib/mysql
      - ./volumes/data/mysql/storage/startup:/docker-entrypoint-initdb.d
      - ./volumes/data/mysql/config/mysql.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - webapp-network


networks:

  webapp-network:
    driver: bridge